# Generated by Django 3.1.4 on 2021-01-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantentry',
            name='country',
        ),
    ]
