# Generated by Django 3.1.4 on 2021-01-11 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_auto_20210111_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantentry',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='airpollution.country'),
            preserve_default=False,
        ),
    ]
