# Generated by Django 3.1.4 on 2021-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0004_pollutantentry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
