# Generated by Django 3.1.4 on 2021-01-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0005_auto_20210127_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.FloatField(),
        ),
    ]
