# Generated by Django 3.1.4 on 2021-02-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0007_pollutant_limit_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutant',
            name='limit_value',
        ),
    ]
