# Generated by Django 3.1.4 on 2021-02-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0009_pollutant_limit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
