# Generated by Django 3.1.4 on 2021-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CURRENT'), (2, 'SAVINGS')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'GIFT'), (4, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RENT'), (2, 'BILLS'), (3, 'CAR'), (4, 'TRAVEL'), (5, 'HEALTH'), (6, 'GROCERIES'), (7, 'FUN'), (8, 'CLOTHES'), (9, 'CHARITY')]),
        ),
    ]
