# Generated by Django 3.1.4 on 2021-05-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0007_income_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
