# Generated by Django 3.1.4 on 2021-05-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0008_income_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='comment_char',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
