# Generated by Django 3.1.4 on 2021-05-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0010_auto_20210510_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='income',
            name='comment_char',
        ),
    ]
