# Generated by Django 3.1.4 on 2021-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0012_auto_20210531_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='date',
            field=models.DateField(default='2001-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
