# Generated by Django 3.1.4 on 2021-10-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0013_auto_20210531_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
