# Generated by Django 3.1.4 on 2021-10-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0014_auto_20211026_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date_end',
            new_name='repetition_end',
        ),
        migrations.RenameField(
            model_name='outcome',
            old_name='date_end',
            new_name='repetition_end',
        ),
    ]
